fitur/urls.py
from django.urls import path
from . import views
app_name = 'fitur'

urlpatterns = [
    path('tipsform/', views.tipsform, name= 'tips_form'),
    path('', views.tipslist, name= 'tips_list'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
   
]

teka/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('simulation/', include('simulation.urls')),
    path('tips/', include('fitur.urls')),
    path('maps/', include('maps.urls')),
    path('feedback/', include('feedback.urls')),
]

fitur/models.py
from django.db import models

# Create your models here.
class Fiturku(models.Model):
    tips = models.CharField(max_length = 500)

    def __str__(self):
        return self.tips

fitur/forms.py
from django import forms
from .models import Fiturku

class Fiturform(forms.ModelForm):


    class Meta :
        model = Fiturku
        fields = [
            'tips'
        ]

        widgets = {
            'tips' : forms.Textarea(attrs={
                'class':'form-style mb-5',
                'rows' : 4,
                'cols' : 25,

                }),
        }

fitur/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404

from .forms import Fiturform
from .models import Fiturku

# Create your views here.
def tipslist(request):
    listp = Fiturku.objects.all()
    return render (request, 'fitur/tips_list.html', {'listp':listp})


def tipsform(request):
    form = Fiturform()
    if request.method == 'POST':
        form = Fiturform(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/tips')

    return render (request, 'fitur/tips_form.html', {'form':form})

fitur/templates/fitur/tips_form.html
{% load static %}

{% include 'header.html' %}
{% block css %}
<link rel="stylesheet" href="{% static 'fitur/tips.css' %}">
{% endblock %}

{% block title %}
<title>Tips - NCovid</title>
{% endblock title %}

<body>
    {% include 'navbar.html' %}
    {% block content %}
    
    <div class="home-container">
      <h2 id= "feature-tagline" style="text-align: center;">TIPS TO PROTECT YOURSELF FROM CORONAVIRUS</h2>
        <!-- <div class="row justify-content-center">
          <div class="col-8"> -->
            <h2>Enter Your Tips Advice Here</h2>
            <hr class="mt-0 mb-4">
            <form method="POST">
              {% csrf_token %}
              {{ form }}
              <br>
              <br>
              <button type="submit" class="btn btn-primary">Submit</button>
              <a type="button" class="btn btn-light" href="{% url 'fitur:tips_list' %}"><b>Back</b></a>
            </form>
          
            <br>
    </div>
       
   
    
</body>
    {% include 'script.html' %}
    {% endblock content %}
    {% include 'footer.html' %}

fitur/templates/fitur/tips_list.html
{% load static %}

{% include 'header.html' %}
{% block css %}
<link rel="stylesheet" href="{% static 'fitur/tips.css' %}">

{% endblock css %}

{% block title %}
<title>Tips - NCovid</title>
{% endblock title %}


<body>
    {% include 'navbar.html' %}
    {% block content %}
    
    <div class="home-container">
      <h2 id= "feature-tagline" style="text-align: center;">TIPS TO PROTECT YOURSELF FROM CORONAVIRUS</h2>
        <div class="row justify-content-center">
          <div class="col-8">
             
                {% for i in listp %}
                <div class="card" style="border-radius: 20px;">
                    <div class="card-body" style="margin: auto;">
                      <div style="margin: auto; text-align: center;"><b>{{ i.tips }}</b></div>
                    </div>
                </div>
                {% endfor %}
              
            <br>
            <a class="btn btn-dark" style="margin-bottom: 40px;" href="{% url 'fitur:tips_form' %}"><b>Add Tips</b></a>
            
        </div>
      </div>
    </div>
    

    {% include 'script.html' %}
    {% endblock content %}
    {% include 'footer.html' %}
</body>